org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
architectury_version=9.1.12
rhino_version=2001.2.3-build.10
kubejs_version=2001.6.5-build.16

mod_id=suixingxiugai
mod_name=Suixing Xiugai
mod_license=GPL-3.0
mod_version=1.0.8
mod_loader=forge
mod_group_id=com.xiaoyu.suixingxiugai
mod_authors=xiaoyu_2009
mod_description=Randomly implement or modify some issues or suggestions in other mods

author_address=https://space.bilibili.com/506597031